# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
        
    - name: Cache SonarQube packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build and analyze
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        
        
    - name: Build with Maven
      run: mvn clean package --file pom.xml
      
    - name: Unit test
      run: mvn test --file pom.xml
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: push to docker hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ahmedrabie90/weather_demo_devops:${{ github.run_number }}

    - name: Update  yaml File with A new Tag
      run: sed "s/IMAGE_VERSION/$IMAGE_VERSION/g"  kubernetes/weather.yaml > kubernetes/new_weather_image.yml

    - name: Create deployment
      uses: Eyevinn/action-eks-kubectl@master
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          IMAGE_VERSION: ${{ github.run_number }}          
          REGION: us-east-1
          CLUSTER: demo
      with:
        args: apply -f kubernetes/new_weather_image.yaml
          
    - name: Get list of Services 
      uses: Eyevinn/action-eks-kubectl@master
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REGION: us-east-1
          CLUSTER: demo    
      with:
        args: get  svc



 
